config/routes.rb
Rails.application.routes.draw do
  
  resources :player_games
  get 'console/index'

  #PLAYERGAMES

  # PLAYERS
  resources :players
  get 'players' => 'player#index'

  # TEAMYEARS
  resources :team_years

  # DEBUG
  get 'debug' => 'debug#index'
  get 'console' => 'console#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
	serialize :team_history, Array
	belongs_to :team_year
	has_many :player_games, dependent: :destroy
	
end

app/models/player_game.rb
class PlayerGame < ApplicationRecord
	belongs_to :player
	#belongs_to :team_year
	belongs_to :opponent, :class_name => "TeamYear"
	belongs_to :team, :class_name => "TeamYear"
    
end

app/models/team_year.rb
class TeamYear < ApplicationRecord
	has_many :players
	has_many :player_games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  def index
  end
end

app/controllers/debug_controller.rb
class DebugController < ApplicationController
  def index

  	@team_years = TeamYear.all
  	@players = Player.all
  	@player_games = PlayerGame.all
  end
end

app/controllers/player_games_controller.rb
class PlayerGamesController < ApplicationController
  before_action :set_player_game, only: [:show, :edit, :update, :destroy]

  # GET /player_games
  # GET /player_games.json
  def index
    @player_games = PlayerGame.all
  end

  # GET /player_games/1
  # GET /player_games/1.json
  def show
  end

  # GET /player_games/new
  def new
    @player_game = PlayerGame.new
  end

  # GET /player_games/1/edit
  def edit
  end

  # POST /player_games
  # POST /player_games.json
  def create
    @player_game = PlayerGame.new(player_game_params)

    respond_to do |format|
      if @player_game.save
        format.html { redirect_to @player_game, notice: 'Player game was successfully created.' }
        format.json { render :show, status: :created, location: @player_game }
      else
        format.html { render :new }
        format.json { render json: @player_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_games/1
  # PATCH/PUT /player_games/1.json
  def update
    respond_to do |format|
      if @player_game.update(player_game_params)
        format.html { redirect_to @player_game, notice: 'Player game was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_game }
      else
        format.html { render :edit }
        format.json { render json: @player_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_games/1
  # DELETE /player_games/1.json
  def destroy
    @player_game.destroy
    respond_to do |format|
      format.html { redirect_to player_games_url, notice: 'Player game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_game
      @player_game = PlayerGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_game_params
      params.require(:player_game).permit(:player_id, :team_id, :date, :opponent_id, :minutes_played, :fg, :fga, :fgp, :threep, :threepa, :threepp, :ft, :fta, :ftp, :orb, :drb, :trb, :ast, :stl, :blk, :tov, :pf, :pts)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all.order(:name)
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :year_of_birth, :position_br, :position_dk, :current_team, :team_history, :points_season_avg, :points_career_avg, :three_pt_shots_made_season_avg, :three_pt_shots_made_career_avg, :assists_season_avg, :assists_career_avg, :offensive_rebounds_season_avg, :defensive_rebounds_season_avg, :offensive_rebounds_career_avg, :defensive_rebounds_career_avg, :steals_season_avg, :steals_career_avg, :blocks_season_avg, :blocks_career_avg, :turnovers_season_avg, :turnovers_career_avg)
    end
end

app/controllers/team_years_controller.rb
class TeamYearsController < ApplicationController
  before_action :set_team_year, only: [:show, :edit, :update, :destroy]

  # GET /team_years
  # GET /team_years.json
  def index
    @team_years = TeamYear.all

    #
    ## Get TeamYears grouped by year
    #
    @year_groups = {}

    # get unique team_years
    @yrs = @team_years.map{|ty| ty.year }.uniq!
    # for each unique season
    @yrs.each{|yr|
      # create the array we'll feed the final hash
      @year_bucket = []
      # for each team_season in each year
      @team_years.where( year: yr).each{|row|
        @year_bucket << row.attributes
      }
      @year_groups[yr.to_sym] = @year_bucket.sort_by{|hsh| -hsh["wins"] }
    }


  end #index

  # GET /team_years/1
  # GET /team_years/1.json
  def show
  end

  # GET /team_years/new
  def new
    @team_year = TeamYear.new
  end

  # GET /team_years/1/edit
  def edit
  end

  # POST /team_years
  # POST /team_years.json
  def create
    @team_year = TeamYear.new(team_year_params)

    respond_to do |format|
      if @team_year.save
        format.html { redirect_to @team_year, notice: 'Team year was successfully created.' }
        format.json { render :show, status: :created, location: @team_year }
      else
        format.html { render :new }
        format.json { render json: @team_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_years/1
  # PATCH/PUT /team_years/1.json
  def update
    respond_to do |format|
      if @team_year.update(team_year_params)
        format.html { redirect_to @team_year, notice: 'Team year was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_year }
      else
        format.html { render :edit }
        format.json { render json: @team_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_years/1
  # DELETE /team_years/1.json
  def destroy
    @team_year.destroy
    respond_to do |format|
      format.html { redirect_to team_years_url, notice: 'Team year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_year
      @team_year = TeamYear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_year_params
      params.require(:team_year).permit(:year, :team, :wins, :losses, :win_percentage, :offensive_rating, :defensive_rating, :season_outcome, :team_url, :team_home_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/console_helper.rb
module ConsoleHelper
end

app/helpers/debug_helper.rb
module DebugHelper
end

app/helpers/player_games_helper.rb
module PlayerGamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/team_years_helper.rb
module TeamYearsHelper
end

app/views/console/index.html.erb
<h1>Console#index</h1>
<p>Find me in app/views/console/index.html.erb</p>



<%= console %>

app/views/debug/index.html.erb
<h1><%= link_to("TeamYears:", team_years_path) %> <%= @team_years.count %></h1>
<p class="col_heads"><%= @team_years.column_names %></p>

<br><br>
<hr>
<br>

<h1><%= link_to('Players:', players_path) %> <%= @players.count %></h1><br>
<p class="col_heads"><%= @players.column_names %></p>

<br><br>
<hr>
<br>

<h1><%= link_to('PlayerGames:', players_path) %> <%= @players.count %></h1><br>
<p class="col_heads"><%= @players.column_names %></p>

<br><br>
<hr>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Hi David</title>
    <%= csrf_meta_tags %>

    <link rel="shortcut icon" href="/old_tablet.jpg"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
    <%= render 'shared/header_nav' %>
    
    <script src="https://d3js.org/d3.v4.min.js"></script>
    
    <%= yield %>

  </body>
</html>

app/views/player_games/_form.html.erb
<%= form_for(player_game) do |f| %>
  <% if player_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player_game.errors.count, "error") %> prohibited this player_game from being saved:</h2>

      <ul>
      <% player_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %>
    <%= f.text_field :player_id %>
  </div>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.text_field :team_id %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :opponent_id %>
    <%= f.text_field :opponent_id %>
  </div>

  <div class="field">
    <%= f.label :minutes_played %>
    <%= f.text_field :minutes_played %>
  </div>

  <div class="field">
    <%= f.label :fg %>
    <%= f.number_field :fg %>
  </div>

  <div class="field">
    <%= f.label :fga %>
    <%= f.number_field :fga %>
  </div>

  <div class="field">
    <%= f.label :fgp %>
    <%= f.text_field :fgp %>
  </div>

  <div class="field">
    <%= f.label :threep %>
    <%= f.number_field :threep %>
  </div>

  <div class="field">
    <%= f.label :threepa %>
    <%= f.number_field :threepa %>
  </div>

  <div class="field">
    <%= f.label :threepp %>
    <%= f.text_field :threepp %>
  </div>

  <div class="field">
    <%= f.label :ft %>
    <%= f.number_field :ft %>
  </div>

  <div class="field">
    <%= f.label :fta %>
    <%= f.number_field :fta %>
  </div>

  <div class="field">
    <%= f.label :ftp %>
    <%= f.text_field :ftp %>
  </div>

  <div class="field">
    <%= f.label :orb %>
    <%= f.number_field :orb %>
  </div>

  <div class="field">
    <%= f.label :drb %>
    <%= f.number_field :drb %>
  </div>

  <div class="field">
    <%= f.label :trb %>
    <%= f.number_field :trb %>
  </div>

  <div class="field">
    <%= f.label :ast %>
    <%= f.number_field :ast %>
  </div>

  <div class="field">
    <%= f.label :stl %>
    <%= f.number_field :stl %>
  </div>

  <div class="field">
    <%= f.label :blk %>
    <%= f.number_field :blk %>
  </div>

  <div class="field">
    <%= f.label :tov %>
    <%= f.number_field :tov %>
  </div>

  <div class="field">
    <%= f.label :pf %>
    <%= f.number_field :pf %>
  </div>

  <div class="field">
    <%= f.label :pts %>
    <%= f.number_field :pts %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_games/edit.html.erb
<h1>Editing Player Game</h1>

<%= render 'form', player_game: @player_game %>

<%= link_to 'Show', @player_game %> |
<%= link_to 'Back', player_games_path %>

app/views/player_games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Player Games</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Team</th>
      <th>Date</th>
      <th>Opponent</th>
      <th>Minutes played</th>
      <th>Fg</th>
      <th>Fga</th>
      <th>Fgp</th>
      <th>Threep</th>
      <th>Threepa</th>
      <th>Threepp</th>
      <th>Ft</th>
      <th>Fta</th>
      <th>Ftp</th>
      <th>Orb</th>
      <th>Drb</th>
      <th>Trb</th>
      <th>Ast</th>
      <th>Stl</th>
      <th>Blk</th>
      <th>Tov</th>
      <th>Pf</th>
      <th>Pts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @player_games.each do |player_game| %>
      <tr>
        <td><%= player_game.player_id %></td>
        <td><%= player_game.team_id %></td>
        <td><%= player_game.date %></td>
        <td><%= player_game.opponent_id %></td>
        <td><%= player_game.minutes_played %></td>
        <td><%= player_game.fg %></td>
        <td><%= player_game.fga %></td>
        <td><%= player_game.fgp %></td>
        <td><%= player_game.threep %></td>
        <td><%= player_game.threepa %></td>
        <td><%= player_game.threepp %></td>
        <td><%= player_game.ft %></td>
        <td><%= player_game.fta %></td>
        <td><%= player_game.ftp %></td>
        <td><%= player_game.orb %></td>
        <td><%= player_game.drb %></td>
        <td><%= player_game.trb %></td>
        <td><%= player_game.ast %></td>
        <td><%= player_game.stl %></td>
        <td><%= player_game.blk %></td>
        <td><%= player_game.tov %></td>
        <td><%= player_game.pf %></td>
        <td><%= player_game.pts %></td>
        <td><%= link_to 'Show', player_game %></td>
        <td><%= link_to 'Edit', edit_player_game_path(player_game) %></td>
        <td><%= link_to 'Destroy', player_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player Game', new_player_game_path %>

app/views/player_games/new.html.erb
<h1>New Player Game</h1>

<%= render 'form', player_game: @player_game %>

<%= link_to 'Back', player_games_path %>

app/views/player_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @player_game.player_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player_game.team_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @player_game.date %>
</p>

<p>
  <strong>Opponent:</strong>
  <%= @player_game.opponent_id %>
</p>

<p>
  <strong>Minutes played:</strong>
  <%= @player_game.minutes_played %>
</p>

<p>
  <strong>Fg:</strong>
  <%= @player_game.fg %>
</p>

<p>
  <strong>Fga:</strong>
  <%= @player_game.fga %>
</p>

<p>
  <strong>Fgp:</strong>
  <%= @player_game.fgp %>
</p>

<p>
  <strong>Threep:</strong>
  <%= @player_game.threep %>
</p>

<p>
  <strong>Threepa:</strong>
  <%= @player_game.threepa %>
</p>

<p>
  <strong>Threepp:</strong>
  <%= @player_game.threepp %>
</p>

<p>
  <strong>Ft:</strong>
  <%= @player_game.ft %>
</p>

<p>
  <strong>Fta:</strong>
  <%= @player_game.fta %>
</p>

<p>
  <strong>Ftp:</strong>
  <%= @player_game.ftp %>
</p>

<p>
  <strong>Orb:</strong>
  <%= @player_game.orb %>
</p>

<p>
  <strong>Drb:</strong>
  <%= @player_game.drb %>
</p>

<p>
  <strong>Trb:</strong>
  <%= @player_game.trb %>
</p>

<p>
  <strong>Ast:</strong>
  <%= @player_game.ast %>
</p>

<p>
  <strong>Stl:</strong>
  <%= @player_game.stl %>
</p>

<p>
  <strong>Blk:</strong>
  <%= @player_game.blk %>
</p>

<p>
  <strong>Tov:</strong>
  <%= @player_game.tov %>
</p>

<p>
  <strong>Pf:</strong>
  <%= @player_game.pf %>
</p>

<p>
  <strong>Pts:</strong>
  <%= @player_game.pts %>
</p>

<%= link_to 'Edit', edit_player_game_path(@player_game) %> |
<%= link_to 'Back', player_games_path %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>YOB</th>
      <th>Position</th>
      <th>Current team</th>
      <th>Active?</th>
      <th>Points avg</th>
      <th>3s avg</th>
      <th>Assists avg</th>
      <th>o-rbnds avg</th>
      <th>d-rebounds avg</th>
      <th>Steals avg</th>
      <th>Blocks avg</th>
      <th>Turnovers avg</th>
      <th>Team history</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.year_of_birth %></td>
        <td><%= player.position_br %></td>
        <td><%= player.current_team %></td>
        <td><%= player.active %></td>
        <td><%= player.points_season_avg %></td>
        <td><%= player.three_pt_shots_made_season_avg %></td>
        <td><%= player.assists_season_avg %></td>
        <td><%= player.offensive_rebounds_season_avg %></td>
        <td><%= player.defensive_rebounds_season_avg %></td>
        <td><%= player.steals_season_avg %></td>
        <td><%= player.blocks_season_avg %></td>
        <td><%= player.turnovers_season_avg %></td>
        <td><%= player.team_history %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Year of birth:</strong>
  <%= @player.year_of_birth %>
</p>

<p>
  <strong>Position br:</strong>
  <%= @player.position_br %>
</p>

<p>
  <strong>Position dk:</strong>
  <%= @player.position_dk %>
</p>

<p>
  <strong>Current team:</strong>
  <%= @player.current_team %>
</p>

<p>
  <strong>Team history:</strong>
  <%= @player.team_history %>
</p>

<p>
  <strong>Points season avg:</strong>
  <%= @player.points_season_avg %>
</p>

<p>
  <strong>Points career avg:</strong>
  <%= @player.points_career_avg %>
</p>

<p>
  <strong>Three pt shots made season avg:</strong>
  <%= @player.three_pt_shots_made_season_avg %>
</p>

<p>
  <strong>Three pt shots made career avg:</strong>
  <%= @player.three_pt_shots_made_career_avg %>
</p>

<p>
  <strong>Assists season avg:</strong>
  <%= @player.assists_season_avg %>
</p>

<p>
  <strong>Assists career avg:</strong>
  <%= @player.assists_career_avg %>
</p>

<p>
  <strong>Offensive rebounds season avg:</strong>
  <%= @player.offensive_rebounds_season_avg %>
</p>

<p>
  <strong>Defensive rebounds season avg:</strong>
  <%= @player.defensive_rebounds_season_avg %>
</p>

<p>
  <strong>Offensive rebounds career avg:</strong>
  <%= @player.offensive_rebounds_career_avg %>
</p>

<p>
  <strong>Defensive rebounds career avg:</strong>
  <%= @player.defensive_rebounds_career_avg %>
</p>

<p>
  <strong>Steals season avg:</strong>
  <%= @player.steals_season_avg %>
</p>

<p>
  <strong>Steals career avg:</strong>
  <%= @player.steals_career_avg %>
</p>

<p>
  <strong>Blocks season avg:</strong>
  <%= @player.blocks_season_avg %>
</p>

<p>
  <strong>Blocks career avg:</strong>
  <%= @player.blocks_career_avg %>
</p>

<p>
  <strong>Turnovers season avg:</strong>
  <%= @player.turnovers_season_avg %>
</p>

<p>
  <strong>Turnovers career avg:</strong>
  <%= @player.turnovers_career_avg %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/shared/_header_nav.html.erb
 <div class="header-nav">
 	<a class="navbar-link" href="/debug">Home</a>
 	<a class="navbar-link" href="/team_years">Team Years</a>
 	<a class="navbar-link" href="/players">Players</a>
 	<a class="navbar-link" href="/player_games">Player Games</a>
 	<a class="navbar-link" href="/player_predictions">Player Predictions</a> 
 	<a class="navbar-link" href="/debug">Debug</a> 
</div>
  
<br/>
<p>&nbsp;</p>
<br/>

app/views/team_years/edit.html.erb
<h1>Editing Team Year</h1>

<%= render 'form', team_year: @team_year %>

<%= link_to 'Show', @team_year %> |
<%= link_to 'Back', team_years_path %>

app/views/team_years/index.html.erb
<h1 align="center">TeamYears</h1>

<chart>
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
var width = 1500;
var height = 600;
var padding = {top: 20, right: 40, bottom: 20, left: 40};
var canvas = d3.select("chart")
              .append("svg")
              .attr("width",width)
              .attr("height",height);

var group = canvas.append("g")
            .attr("transform", "translate(" + padding.left + "," + padding.top + ")");

var x = d3.scaleLinear()
    .domain([0,82])
    .range([padding.left, width-padding.right*2]);
    //.padding(1);

var y = d3.scaleLinear()
    .domain([50000000,170000000])
    .range([height-padding.bottom*3,padding.top]);

group.append("g")
  .attr("transform", "translate(" + padding.left + ",0)")
  .attr("class", "axis")
  .call(d3.axisLeft(y)
      .ticks(10));

group.append("g")
  .attr("transform", "translate(0,550)")
  .attr("class", "axis")
  .call(d3.axisBottom(x)
      .ticks(5));

</script>
</chart>

<br><hr><br>

<h2 align="center">Season Results</h2>
<table class="thirds-table">
  <tbody>
    <% counter = 0 %>
    <% (@year_groups.length/3).times do %>
      <tr>
        <% 3.times do %>
          <td>
            <% year = @year_groups.keys[counter] %>
            <br><br><hr><h2 align="center"><%= year %></h2><br>
            <table class="thirds-table">
              <tbody>
                   <tr>
                    <th> &nbsp; </th>
                    <th> W </th>
                    <th> L </th>
                    <th> Win % </th>
                    <th> &nbsp; </th>
                  </tr>
                <% @year_groups[year].each{ |teamrow| %>
                  <tr>
                    <td class="thirds-cell"><%= teamrow["team"] %></td>
                    <td class="thirds-cell"><%= teamrow["wins"] %></td>
                    <td class="thirds-cell"><%= teamrow["losses"] %></td>
                    <td class="thirds-cell"><%= teamrow["win_percentage"] %></td>
                    <td class="thirds-cell"><%= teamrow["season_outcome"] %></td>
                  </tr>
                <% } %>
              </tbody>
            </table>
            <% counter += 1 %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>
<hr>
<br><br>
<center><h1>Raw Table: TeamYears</h1></center>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Team</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Win %</th>
      <th>Offensive rating</th>
      <th>Defensive rating</th>
      <th>Season outcome</th>
      <th>Team url</th>
      <th>Team home url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_years.each do |team_year| %>
      <tr>
        <td><%= team_year.year %></td>
        <td><%= team_year.team %></td>
        <td><%= team_year.wins %></td>
        <td><%= team_year.losses %></td>
        <td><%= team_year.win_percentage %></td>
        <td><%= team_year.offensive_rating %></td>
        <td><%= team_year.defensive_rating %></td>
        <td><%= team_year.season_outcome %></td>
        <td><%= team_year.team_url %></td>
        <td><%= team_year.team_home_url %></td>
        <td><%= link_to 'Show', team_year %></td>
        <td><%= link_to 'Edit', edit_team_year_path(team_year) %></td>
        <td><%= link_to 'Destroy', team_year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Year', new_team_year_path %>

app/views/team_years/new.html.erb
<h1>New Team Year</h1>

<%= render 'form', team_year: @team_year %>

<%= link_to 'Back', team_years_path %>

app/views/team_years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @team_year.year %>
</p>

<p>
  <strong>Team:</strong>
  <%= @team_year.team %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @team_year.wins %>
</p>

<p>
  <strong>Losses:</strong>
  <%= @team_year.losses %>
</p>

<p>
  <strong>Win percentage:</strong>
  <%= @team_year.win_percentage %>
</p>

<p>
  <strong>Offensive rating:</strong>
  <%= @team_year.offensive_rating %>
</p>

<p>
  <strong>Defensive rating:</strong>
  <%= @team_year.defensive_rating %>
</p>

<p>
  <strong>Season outcome:</strong>
  <%= @team_year.season_outcome %>
</p>

<p>
  <strong>Team url:</strong>
  <%= @team_year.team_url %>
</p>

<p>
  <strong>Team home url:</strong>
  <%= @team_year.team_home_url %>
</p>

<%= link_to 'Edit', edit_team_year_path(@team_year) %> |
<%= link_to 'Back', team_years_path %>